# Generated by Django 3.0.4 on 2020-04-14 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('zip_code', models.IntegerField(verbose_name='code_postal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone',
            },
        ),
        migrations.CreateModel(
            name='Hives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('year', models.IntegerField(default=2020, verbose_name='Année de la reine')),
                ('origin', models.CharField(default='Eleveur', max_length=100, verbose_name='origine')),
                ('hive_type', models.CharField(choices=[('Dadant', 'Dadant'), ('Langstroth', 'Langstroth'), ('Warré', 'Warré')], max_length=100, verbose_name='nom du type de ruche')),
                ('frame_number', models.IntegerField(default='10', verbose_name='nombre de cadre')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.Zones')),
            ],
            options={
                'verbose_name': 'ruche',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='date de création')),
                ('details', models.TextField(max_length=1000, verbose_name='détails')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.Hives')),
            ],
            options={
                'verbose_name': 'Historique',
                'ordering': ['-created_at'],
            },
        ),
    ]
